# Generated by Django 4.2.21 on 2025-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=100, unique=True)),
                ('select_uac', models.CharField(default='uac_basic.xml', max_length=100)),
                ('select_uas', models.CharField(default='uas_basic.xml', max_length=100)),
                ('uac_remote', models.GenericIPAddressField(default='1.1.1.1')),
                ('uac_remote_port', models.PositiveIntegerField(default=5060)),
                ('uas_remote', models.GenericIPAddressField(default='2.2.2.2')),
                ('uas_remote_port', models.PositiveIntegerField(default=5060)),
                ('local_addr', models.GenericIPAddressField(default='3.3.3.3')),
                ('src_port_uac', models.PositiveIntegerField(default=5060)),
                ('src_port_uas', models.PositiveIntegerField(default=5062)),
                ('protocol_uac', models.CharField(choices=[('u1', 'UDP'), ('tn', 'TCP')], default='u1', max_length=10)),
                ('protocol_uas', models.CharField(choices=[('u1', 'UDP'), ('tn', 'TCP')], default='u1', max_length=10)),
                ('called_party_number', models.CharField(blank=True, max_length=30)),
                ('calling_party_number', models.CharField(blank=True, max_length=30)),
                ('total_no_of_calls', models.PositiveIntegerField(default=1)),
                ('cps', models.PositiveIntegerField(default=1, null=True)),
                ('stun_server', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
