# Generated by Django 4.2.21 on 2025-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easySIPp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UacAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uac_key', models.CharField(default='uac_1', max_length=5, unique=True)),
                ('uac_config_name', models.CharField(default='Default UAC', max_length=28, unique=True)),
                ('select_uac', models.CharField(default='uac_basic.xml', max_length=100)),
                ('uac_remote', models.GenericIPAddressField(default='1.1.1.1')),
                ('uac_remote_port', models.PositiveIntegerField(default=5060)),
                ('uac_local_addr', models.GenericIPAddressField(default='3.3.3.3')),
                ('src_port_uac', models.PositiveIntegerField(default=5060)),
                ('protocol_uac', models.CharField(choices=[('u1', 'UDP'), ('tn', 'TCP')], default='u1', max_length=10)),
                ('called_party_number', models.CharField(blank=True, max_length=30)),
                ('calling_party_number', models.CharField(blank=True, max_length=30)),
                ('total_no_of_calls', models.PositiveIntegerField(default=1)),
                ('cps', models.PositiveIntegerField(default=1, null=True)),
                ('stun_server', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active_config', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UasAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uas_key', models.CharField(default='uas_1', max_length=5, unique=True)),
                ('uas_config_name', models.CharField(default='Default UAS', max_length=28, unique=True)),
                ('select_uas', models.CharField(default='uas_basic.xml', max_length=100)),
                ('uas_remote', models.GenericIPAddressField(default='2.2.2.2')),
                ('uas_remote_port', models.PositiveIntegerField(default=5060)),
                ('uas_local_addr', models.GenericIPAddressField(default='3.3.3.3')),
                ('src_port_uas', models.PositiveIntegerField(default=5062)),
                ('protocol_uas', models.CharField(choices=[('u1', 'UDP'), ('tn', 'TCP')], default='u1', max_length=10)),
                ('is_active_config', models.BooleanField(default=False)),
            ],
        ),
    ]
